/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.calculadora1;

/**
 *
 * @author Kevin Alfonso
 */
public class calculadora extends javax.swing.JPanel {
    
    private boolean punto=true;
    String valor1, valor2, signo, contenido;
     Double resultado;
     
     
    

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtmostar = new javax.swing.JTextField();
        btncuatro = new javax.swing.JButton();
        btnsiete = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btntres = new javax.swing.JButton();
        btnmasmenos = new javax.swing.JButton();
        btnunox = new javax.swing.JButton();
        btnocho = new javax.swing.JButton();
        btncinco = new javax.swing.JButton();
        btndo = new javax.swing.JButton();
        btncero = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnnueve = new javax.swing.JButton();
        btnseis = new javax.swing.JButton();
        btnuno = new javax.swing.JButton();
        btnxy = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btnex = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btnmultiplicacion = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setToolTipText("Calculadora");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmostarActionPerformed(evt);
            }
        });
        add(txtmostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 50));

        btncuatro.setText("4");
        btncuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuatroActionPerformed(evt);
            }
        });
        add(btncuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 30));

        btnsiete.setText("7");
        btnsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsieteActionPerformed(evt);
            }
        });
        add(btnsiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 30));

        btnraiz.setText("Raiz ");
        btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizActionPerformed(evt);
            }
        });
        add(btnraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 30));

        btntres.setText("3");
        btntres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntresActionPerformed(evt);
            }
        });
        add(btntres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 30));

        btnmasmenos.setText("+-");
        btnmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasmenosActionPerformed(evt);
            }
        });
        add(btnmasmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, 30));

        btnunox.setText("1/x");
        btnunox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunoxActionPerformed(evt);
            }
        });
        add(btnunox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 30));

        btnocho.setText("8");
        btnocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnochoActionPerformed(evt);
            }
        });
        add(btnocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, 30));

        btncinco.setText("5 ");
        btncinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncincoActionPerformed(evt);
            }
        });
        add(btncinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 30));

        btndo.setText(" 2");
        btndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoActionPerformed(evt);
            }
        });
        add(btndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 30));

        btncero.setText("0");
        btncero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceroActionPerformed(evt);
            }
        });
        add(btncero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 30));

        btnx2.setText("x^2");
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });
        add(btnx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 30));

        btnnueve.setText("9");
        btnnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnueveActionPerformed(evt);
            }
        });
        add(btnnueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, 30));

        btnseis.setText("6");
        btnseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseisActionPerformed(evt);
            }
        });
        add(btnseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, 30));

        btnuno.setText("1");
        btnuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunoActionPerformed(evt);
            }
        });
        add(btnuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 60, 30));

        btnxy.setText("x^y");
        btnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxyActionPerformed(evt);
            }
        });
        add(btnxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 60, 30));

        btnsuma.setText("+");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });
        add(btnsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 60, 70));

        btnresta.setText("-");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });
        add(btnresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 60, 30));

        btnpunto.setText(".");
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 60, 30));

        btnex.setText("e^x");
        btnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexActionPerformed(evt);
            }
        });
        add(btnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 60, 30));

        btnborrar.setText("<---");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 140, 30));

        btnc.setText("C");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        add(btnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 60, 110));

        btndivision.setText("/");
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });
        add(btndivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, 30));

        btnigual.setText("=");
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 60, 30));

        btnmultiplicacion.setText("X");
        btnmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicacionActionPerformed(evt);
            }
        });
        add(btnmultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 60, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtmostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmostarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmostarActionPerformed

    private void btnunoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunoxActionPerformed
         // TODO add your handling code here:
         contenido=txtmostar.getText();
        if(contenido.length()>0){
            resultado=1/(Double.parseDouble(contenido));
            txtmostar.setText(resultado.toString());
    }//GEN-LAST:event_btnunoxActionPerformed
    }
    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        // TODO add your handling code here:
     contenido=txtmostar.getText();
        if(contenido.length()>0){
            resultado=Math.pow(Double.parseDouble(contenido),2);
            txtmostar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseisActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"6");
  
    }//GEN-LAST:event_btnseisActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
         // TODO add your handling code here:
         if(!txtmostar.getText().equals(" ")){
             valor1=txtmostar.getText();
             signo="+";
             txtmostar.setText("");
         }
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicacionActionPerformed
        // TODO add your handling code here:
        if(!txtmostar.getText().equals(" ")){
             valor1=txtmostar.getText();
             signo="*";
             txtmostar.setText("");
         }
    }//GEN-LAST:event_btnmultiplicacionActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
        txtmostar.setText("");
    }//GEN-LAST:event_btncActionPerformed

    private void btnceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceroActionPerformed
        // TODO add your handling code here:
        txtmostar.setText(txtmostar.getText()+"0");
        
        
    }//GEN-LAST:event_btnceroActionPerformed

    private void btntresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntresActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"3");
        
    }//GEN-LAST:event_btntresActionPerformed

    private void btnunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunoActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"1");
        
    }//GEN-LAST:event_btnunoActionPerformed

    private void btndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"2");
        
    }//GEN-LAST:event_btndoActionPerformed

    private void btncuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuatroActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"4");
        
    }//GEN-LAST:event_btncuatroActionPerformed

    private void btncincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncincoActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"5");
        
    }//GEN-LAST:event_btncincoActionPerformed

    private void btnsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsieteActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"7");
        
    }//GEN-LAST:event_btnsieteActionPerformed

    private void btnochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnochoActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"8");
        
    }//GEN-LAST:event_btnochoActionPerformed

    private void btnnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnueveActionPerformed
        // TODO add your handling code here:
                txtmostar.setText(txtmostar.getText()+"9");
        
    }//GEN-LAST:event_btnnueveActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        // TODO add your handling code here:
        contenido=txtmostar.getText();
        if(contenido.length()<=0){
            txtmostar.setText("0.");
        }else 
           if(txtmostar.getText().contains(".")){
               
           }else{
               txtmostar.setText(txtmostar.getText()+".");
        punto=false;
           }
    }//GEN-LAST:event_btnpuntoActionPerformed
public static String operaciones (String valor1,String valor2, String signo ){
    Double resultadocalc=0.0;
    String respuesta;
    
    if(signo.equals("+")){
        resultadocalc=Double.parseDouble(valor1)+Double.parseDouble(valor2);
    }else  if(signo.equals("-")){
         resultadocalc=Double.parseDouble(valor1)-Double.parseDouble(valor2);
    }else  if(signo.equals("*")){
         resultadocalc=Double.parseDouble(valor1)*Double.parseDouble(valor2);
    }else  if(signo.equals("/")){
         resultadocalc=Double.parseDouble(valor1)/Double.parseDouble(valor2);
    }else  if(signo.equals("x^y")){
         resultadocalc=Math.pow(Double.parseDouble(valor1),Double.parseDouble(valor2));
    }
    respuesta=resultadocalc.toString();
    return respuesta;
}
    private void btnmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasmenosActionPerformed
        // TODO add your handling code here:
        contenido=txtmostar.getText();
        if(contenido.length()>0){
            resultado=(-1)* Double.parseDouble(contenido);
          txtmostar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnmasmenosActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        // TODO add your handling code here:
        if(!txtmostar.getText().equals(" ")){
             valor1=txtmostar.getText();
             signo="-";
             txtmostar.setText("");
         }
    }//GEN-LAST:event_btnrestaActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        // TODO add your handling code here:
        if(!txtmostar.getText().equals(" ")){
             valor1=txtmostar.getText();
             signo="/";
             txtmostar.setText("");
         }
    }//GEN-LAST:event_btndivisionActionPerformed

    private void btnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxyActionPerformed
        // TODO add your handling code here:
        if(!txtmostar.getText().equals(" ")){
             valor1=txtmostar.getText();
             signo="x^y";
             txtmostar.setText("");
         }
    }//GEN-LAST:event_btnxyActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        // TODO add your handling code here:
        String resultadototal;
        valor2=txtmostar.getText();
         if(!valor2.equals(" ")){
            resultadototal=operaciones(valor1, valor2, signo);
             txtmostar.setText(resultadototal);
    }//GEN-LAST:event_btnigualActionPerformed
    }
    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        contenido=txtmostar.getText();
        if(contenido.length()>0){
            contenido=contenido.substring(0,contenido.length()-1);;
            txtmostar.setText(contenido);
        }
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizActionPerformed
        // TODO add your handling code here:
        contenido=txtmostar.getText();
        if(contenido.length()>0){
            resultado=Math.exp(Double.parseDouble(contenido));
            txtmostar.setText(resultado.toString());
        }
        
    }//GEN-LAST:event_btnraizActionPerformed

    private void btnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexActionPerformed
        // TODO add your handling code here:
      contenido=txtmostar.getText();
        if(contenido.length()>0){
            resultado=1/(Double.parseDouble(contenido));
            txtmostar.setText(resultado.toString());
    }//GEN-LAST:event_btnexActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btncero;
    private javax.swing.JButton btncinco;
    private javax.swing.JButton btncuatro;
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btndo;
    private javax.swing.JButton btnex;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnmasmenos;
    private javax.swing.JButton btnmultiplicacion;
    private javax.swing.JButton btnnueve;
    private javax.swing.JButton btnocho;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnseis;
    private javax.swing.JButton btnsiete;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton btntres;
    private javax.swing.JButton btnuno;
    private javax.swing.JButton btnunox;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnxy;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtmostar;
    // End of variables declaration//GEN-END:variables
}
